### ISSUE TITLE
Make the colors of the legend more distinguishable

### ISSUE THREAD

**Issue by alikn** [alikn/project530#15]

**Comment by alikn** [comment]
Lets reserve the red color for the selected sector to be clearly distinguishable. So no close to red color for the legends.

**Comment by JasvirBhathal** [comment]
are we keeping the color of miscellaneous sources as black?

**Comment by yasminf** [comment]
@JasvirBhathal no i've changed it to green

**Comment by JasvirBhathal** [comment]
Reviewed
