### ISSUE TITLE
Change the colors of the lineGraph background and find one which makes better contrast

### ISSUE THREAD

**Issue by alikn** [alikn/project530#16]

**Comment by twizzyyanki** [comment]
@alikn @yasminf @JasvirBhathal With the lines of the graph colored, I think it is better to use a white background. What do you think?

**Comment by alikn** [comment]
I like white for the background of the graph. We should do some speculation for the background of the page too.

**Comment by yasminf** [comment]
changed to light grey as discussed so closing for now
