### ISSUE TITLE
Creating some sort of connection between lineGraph and the legend

### ISSUE THREAD

**Issue by alikn** [alikn/project530#22]
e.g. once user hovers over a line, the associated sector group "glows" in the legend.

**Comment by alikn** [comment]
@yasminf  I added the code which adds a class called "filterDistinct" to the corresponding filter "li" tag whenever a line is hovered in the lineGraph. Could you please style the class appropriately to make it fit nicely into page?
Thanks.

**Comment by yasminf** [comment]
fixed
