### ISSUE TITLE
Make the lines of the graph smoother

### ISSUE THREAD

**Issue by twizzyyanki** [alikn/project530#26]
I found out how to do this

 line = d3.svg.line()
                .interpolate("basis") //change basis to linear to get back the straight line graph
                .x(function (d) {
                    return x(d.x);
                })
                .y(function (d) {
                    return y(d.y);
                });

**Comment by alikn** [comment]
It definitely looks nicer visually this way, but I am not sure if it is scientifically the right thing to do. For now let's keep the interpolation.
