### ISSUE TITLE
The line graph does not scale properly

### ISSUE THREAD

**Issue by yasminf** [alikn/project530#32]
For some materials eg sox the top part of the line graph is not displayed and appears cut off. Additionally the scale on the y-axsis remains the same for all materials. Eg TPM does not have data points higher than 250,000 so maximum value on y-axis should be 250,000 and not 450,000. 
- Not sure how this will impact the zoom.

**Comment by twizzyyanki** [comment]
@yasminf Is this not the same as issue #10
