### ISSUE TITLE
When the line graph loads, all the lines should be coloured ...

### ISSUE THREAD

**Issue by twizzyyanki** [alikn/project530#33]
In addition all the legends should be shown in colour as they are now. Clicking on a legend should toggle between hiding and showing the corresponding lines

**Comment by alikn** [comment]
That is not what we decided in our meeting with Bruce and Bob. Based on the discussions, all the lines should be in their sector group color as default and go to grey once the sector group is deselected.

**Comment by alikn** [comment]
Fixed based on the explanation.

**Comment by yasminf** [comment]
tested works closing
