### ISSUE TITLE
Why does the bar chart display as shown in the picture?

### ISSUE THREAD

**Issue by twizzyyanki** [alikn/project530#34]
![cics 530 group 5](https://cloud.githubusercontent.com/assets/7083648/6931979/76b58c48-d7c8-11e4-8dda-d99cde198ef7.png)

I don't seem to understand why there are 2 levels of pm25. Could @yasminf or @alikn explain please

**Comment by yasminf** [comment]
@twizzyyanki are u seeing this issue even after pulling the latest commit? if so for what material? i cant seem to recreate it on my end

**Comment by twizzyyanki** [comment]
@yasminf my bad. I refreshed the page and it worked fine

**Comment by JasvirBhathal** [comment]
tested
