### ISSUE TITLE
Add some description of what tonnes of the pollutants actually mean to the viewer

### ISSUE THREAD

**Issue by twizzyyanki** [alikn/project530#45]

**Comment by twizzyyanki** [comment]
![cics 530 group 53](https://cloud.githubusercontent.com/assets/7083648/7001387/71e8eb4c-dbec-11e4-9ca6-5eef117a3142.png)

@yasminf @alikn how will the user know what that image means?

**Comment by yasminf** [comment]
@alikin, @twizzyyanki , @JasvirBhathal do you think its worth leaving in the general descriptions by default and just showing the avgs on hover the legend looks kind off empty with just the titles at the moment

**Comment by alikn** [comment]
I think this is one of the cases in which the less is more! Having sparse amount of writing helps user not to feel overwhelmed. Moreover, if we add those, once the user hovers over a title, the height of the legend might go above the height of the lineGraph and therefore the barChart and infoBox might dynamically get pushed a little bit down.

**Comment by alikn** [comment]
@twizzyyanki the small truck is equivalent to a weight of 250 tonnes. This is one of the things we need to mention in the tour and also as a note in the bottom of the page among other references. This is to put the tonne into some sort of meaning for the user.

**Comment by yasminf** [comment]
we still need to add this info to the footer and maybe use a different image for the trucks so im leaving it open for  now

**Comment by yasminf** [comment]
@alikn did you add the meaning of the trucks to the tour
