### ISSUE TITLE
all tooltips on map, barchart, and line graph should follow same styling

### ISSUE THREAD

**Issue by yasminf** [alikn/project530#55]

**Comment by twizzyyanki** [comment]
@yasminf Could you explain more? I don't get

**Comment by yasminf** [comment]
@twizzyyanki currently if you hover over items in the bubble chart area or the map area they are different from the ones we have on the line graph  as shown below
![image](https://cloud.githubusercontent.com/assets/7033274/7082177/14ca19de-df04-11e4-8d11-817646203a67.png)

**Comment by JasvirBhathal** [comment]
fixed
