### ISSUE TITLE
Center the legend for Tonnes in the lineGraph and change it to Tonnes/Year

### ISSUE THREAD

**Issue by alikn** [alikn/project530#59]

**Comment by twizzyyanki** [comment]
@alikn The problem with centering is that when the scale gets to 7 digits, it overlaps with the legend as shown below

![cics 530 group 545](https://cloud.githubusercontent.com/assets/7083648/7102651/c5c22e9c-e03b-11e4-84f4-cf4d8907f80a.png)

Should I still center it. Moving the legend to the left, will cut it out from the page

**Comment by alikn** [comment]
I c. Can't we more the label a bit further away? It's position is getting set somewhere in the code, right?

**Comment by twizzyyanki** [comment]
Fixed

**Comment by alikn** [comment]
Great.
