### ISSUE TITLE
Legend info do not appear

### ISSUE THREAD

**Issue by alikn** [alikn/project530#64]
The info under legend titles (average and small truck!) does not appear. I think the id or class of filters were probably changed.

**Comment by yasminf** [comment]
ok looking into this now

**Comment by yasminf** [comment]
@alikn I have added a fix for this so please go ahead and test
- on another note I am having trouble getting the highlightFilter events to work ... the filterDistinct class is not being added to elements on hover not sure if this a related issue but any ideas?

**Comment by yasminf** [comment]
@alikn fixed the above issue also please re-test.
