### ISSUE TITLE
Linegraph rescaling

### ISSUE THREAD

**Issue by alikn** [alikn/project530#66]
Write a function which receives the maximum Y value and re-scales the line graph accordingly. The line graph should animate (not jump) toward the final state [I suspect the animate() method of d3 can be used for the animation part]. 
This will be the function that would be called on the event the user selects/deselects a sector group and the maximum value for all the present sector groups will be given to this function.

**Comment by twizzyyanki** [comment]
I added a rescale function to do this

**Comment by alikn** [comment]
Ifeanyi, take a look at my recent commit. Every time a user selects/deselects a sector group, I call your function with a new max, but rescaling does not happen.
