### ISSUE TITLE
Consistency issue of the data used for the map

### ISSUE THREAD

**Issue by alikn** [alikn/project530#73]
There is some consistency issue between PM2.5, PM10 and TPM. The TPM is the summation of the particles with different sizes (including PM2.5 and PM10). For example, for Canada, the PM2.5 and P10 values are very small according to the color coding of the map so one would conclude the TPM value for Canada should be small as well. But it is not the case at all and in fact it is pretty high.

**Comment by alikn** [comment]
Ifeanyi, can you take care of this one?

**Comment by twizzyyanki** [comment]
I will take a look this weekend. The unit of measurement is different that is why it looks like that. PM2.5 & PM10 are in ug/m3 while TPM is in g/year
